[package]
name = "srp71"
version = "0.1.0"
authors = ["Matthew Piziak <matthew.piziak@gmail.com>"]

[dependencies]
itertools = "0.5.4"
time = "0.1"

[dependencies.zkill]
git = "https://github.com/matthew-piziak/zkill"

[dependencies.eve-type-id]
git = "https://github.com/matthew-piziak/eve-type-id"